import { useState } from 'react';
import type { SavedLine } from '../App';
import type { VoicePreset } from '../core/voicePreset';
import { exportConnections, importConnections, downloadFile } from '../core/backup';
import { VoicePanel } from './VoicePanel';
interface Props { lines: SavedLine[]; voice: VoicePreset; onVoice: (preset: VoicePreset) => Promise<void>; onImport: (lines: SavedLine[]) => void; onClear: () => Promise<void>; onClose: () => void; voiceOnly?: boolean; }
export function DeviceSettings({lines,voice,onVoice,onImport,onClear,onClose,voiceOnly=false}:Props) {
 const [password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [preview,setPreview]=useState<SavedLine[]|null>(null),[file,setFile]=useState<File|null>(null),[tab,setTab]=useState(voiceOnly?'voice':'device');
 const [mode,setMode]=useState<'export'|'import'>('export'),[selected,setSelected]=useState<string[]>(lines.map(l=>l.id));
 const changeMode=(next:'export'|'import')=>{setMode(next);setPassword('');setConfirmation('');setPreview(null);setFile(null);setMessage('');};
 const selection=(line:SavedLine)=>selected.includes(line.id);
 const status=(line:SavedLine)=>{const existing=lines.find(l=>l.id===line.id);return !existing?'Ready to restore':existing.passcode===line.passcode?'Already saved':'Conflicting secret — cannot merge';};
 const chosen=preview?.filter(selection)||[];
 return <div className="modal-backdrop" onClick={()=>{if(!busy)onClose();}}><section className="modal-card device-settings" onClick={e=>e.stopPropagation()}><div className="modal-header"><h2>{voiceOnly?'Voice effects':'Your device'}</h2><button disabled={busy} aria-label="Close settings" className="btn btn-secondary" onClick={onClose}>✕</button></div>
 {!voiceOnly&&<div className="settings-tabs"><button disabled={busy} className={`btn ${tab==='device'?'btn-primary':'btn-secondary'}`} onClick={()=>setTab('device')}>Data & backup</button><button disabled={busy} className={`btn ${tab==='voice'?'btn-primary':'btn-secondary'}`} onClick={()=>setTab('voice')}>Voice effects</button></div>}
 {tab==='voice'?<VoicePanel value={voice} onApply={onVoice}/>:<>
 <h3>Your connections, wherever you go.</h3><p className="settings-copy">A backup restores the same invitations. To invite a new person, use Share invite in the Phone Book instead.</p>
 <div className="settings-tabs"><button disabled={busy} className={`btn ${mode==='export'?'btn-primary':'btn-secondary'}`} onClick={()=>changeMode('export')}>Create backup</button><button disabled={busy} className={`btn ${mode==='import'?'btn-primary':'btn-secondary'}`} onClick={()=>changeMode('import')}>Restore backup</button></div>
 {mode==='export'?<>
 <h3>1. Choose connections</h3><div className="transfer-list">{lines.map(l=><label key={l.id} className="transfer-item"><input type="checkbox" checked={selection(l)} onChange={e=>setSelected(e.target.checked?[...selected,l.id]:selected.filter(id=>id!==l.id))}/><span>{l.name}</span></label>)}</div>
 <h3>2. Protect your backup</h3><p className="settings-copy">Use a unique password of at least 12 characters. The encrypted file contains invitation secrets. We cannot recover its password.</p>
 <label className="input-label">Backup password<input aria-label="Backup password" className="input-field" type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>
 <label className="input-label">Confirm password<input aria-label="Confirm backup password" className="input-field" type="password" autoComplete="new-password" value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label>
 <button className="btn btn-share btn-full" disabled={busy||!lines.some(selection)} onClick={async()=>{setMessage('');if(password!==confirmation){setMessage('Passwords do not match.');return;}setBusy(true);try{downloadFile('imicall-connections.imicall',await exportConnections(lines.filter(selection),password));setPassword('');setConfirmation('');setMessage('Backup download started. Check your Downloads and test restoring it before deleting your original contacts.');}catch(e){setMessage(e instanceof Error?e.message:'Export failed');}finally{setBusy(false);}}}>{busy?'Encrypting…':'Export connections'}</button>
 </>:<>
 <h3>1. Select a backup</h3><label className="btn btn-secondary file-button">Choose backup file<input disabled={busy} type="file" accept=".imicall,.json,application/json" onChange={e=>{setPreview(null);setMessage('');const f=e.target.files?.[0];if(f&&f.size>2000000){setMessage('Backup is too large.');setFile(null);}else setFile(f||null);e.target.value='';}}/></label><p className="settings-copy">{file?.name||'Your file stays in this browser. It is not uploaded.'}</p>
 <h3>2. Unlock and review</h3><label className="input-label">Backup password<input aria-label="Backup password" className="input-field" type="password" autoComplete="off" value={password} onChange={e=>setPassword(e.target.value)}/></label>
 <button className="btn btn-primary" disabled={busy||!file||!password} onClick={async()=>{if(!file)return;setBusy(true);setMessage('');try{const list=await importConnections(await file.text(),password);setPreview(list);setSelected(list.filter(l=>status(l)==='Ready to restore').map(l=>l.id));setPassword('');}catch(e){setMessage(e instanceof Error?e.message:'Cannot unlock backup');}finally{setBusy(false);}}}>{busy?'Unlocking…':'Review backup'}</button>
 {preview&&<div className="backup-preview"><h3>3. Restore selected connections</h3><div className="transfer-list">{preview.map(l=><label key={l.id} className="transfer-item"><input type="checkbox" disabled={status(l)!=='Ready to restore'} checked={selection(l)} onChange={e=>setSelected(e.target.checked?[...selected,l.id]:selected.filter(id=>id!==l.id))}/><span>{l.name}<small>{status(l)}</small></span></label>)}</div><p className="settings-copy">Existing contacts stay unchanged. This restores old invitations; it does not generate new secrets. The other person must still have the matching invitation.</p><button className="btn btn-primary" disabled={!chosen.length} onClick={()=>{try{onImport(chosen);setPreview(null);setFile(null);setMessage(`${chosen.length} connections restored. Open one in your Phone Book to call.`);}catch(e){setMessage(e instanceof Error?e.message:'Import failed');}}}>Merge connections</button></div>}
 </>}
 {message&&<p role="status" className="settings-copy">{message}</p>}
 <details className="transfer-guide"><summary>What happens after deleting and restoring?</summary><p>Remove deletes your browser’s copy only. The other person keeps theirs. If both people delete it, restoring the same backup or private invite on both devices makes the connection available again when both are online.</p><p>A backup is a copy of access, not a transfer. Old copies are not revoked by deleting or importing. If an invitation leaks, create a new connection and privately share its new invite. Do not use or restore the old one. At most two participants can join a room at once; that does not prove their identity.</p></details>
 <h3>Leave this device clean.</h3><p className="settings-copy">Removes contacts, presets, notification subscription and offline cache here. It does not erase anyone else’s browser or downloaded backups.</p>
 <button className="btn btn-danger btn-full" disabled={busy} onClick={async()=>{if(!window.confirm('Delete all ImiCall data and its offline cache from this browser? Export and verify a backup first. Other devices and downloaded backups are not erased.'))return;setBusy(true);try{await onClear();onClose();}catch(e){setMessage(e instanceof Error?e.message:'Could not clear all data.');}finally{setBusy(false);}}}>Clear all ImiCall data</button>
 </>}
 </section></div>;
}
