import { useState } from 'react';
import { NATURAL, VOICE_PRESETS, VoicePreset, validateVoicePreset } from '../core/voicePreset';
import { downloadFile } from '../core/backup';
import { localStore } from '../core/localStore';
export function VoicePanel({ value, onApply }: { value: VoicePreset; onApply: (value: VoicePreset) => Promise<void> }) {
 const [draft, setDraft] = useState(value), [busy, setBusy] = useState(false), [error, setError] = useState('');
 const [saved, setSaved] = useState<VoicePreset[]>(() => { try { return JSON.parse(localStore.getItem('imicall_voice_presets') || '[]').slice(0,20).map(validateVoicePreset); } catch { return []; } });
 const [imported, setImported] = useState<VoicePreset|null>(null);
 const save = (preset:VoicePreset) => {
  const p=validateVoicePreset(preset);
  if(saved.some(s=>s.name===p.name)&&!window.confirm('Replace your saved preset with this name?'))return;
  const next=[p,...saved.filter(s=>s.name!==p.name)].slice(0,20);setSaved(next);localStore.setItem('imicall_voice_presets',JSON.stringify(next));setError('Preset saved on this device. It has not been applied to your call.');
 };
 const apply = async (preset: VoicePreset) => { setBusy(true); setError(''); try { await onApply(validateVoicePreset(preset)); } catch (e) { setError(e instanceof Error ? e.message : 'Filter could not start. Microphone stays muted.'); } finally { setBusy(false); } };
 return <section className="voice-panel"><h3>Voice effects</h3><p className="settings-copy">Natural voice is the default every time you open ImiCall. Effects run on this device and can change during a call.</p>
  <div className="preset-grid">{[...VOICE_PRESETS,...saved].map((p,i)=><button key={i} className={`btn btn-secondary ${draft.name===p.name?'chosen':''}`} onClick={()=>setDraft(p)}>{p.name}</button>)}</div>
  <label className="input-label">Preset name<input className="input-field" value={draft.name} maxLength={40} onChange={e=>setDraft({...draft,name:e.target.value})} /></label>
  <label className="range-label">Pitch <strong>{draft.pitch} semitones</strong><input aria-label="Pitch" type="range" min="-7" max="7" step="1" value={draft.pitch} onChange={e=>setDraft({...draft,pitch:+e.target.value,mix:1})} /></label>
  <label className="range-label">Robot tone <strong>{draft.carrier} Hz</strong><input aria-label="Robot tone" type="range" min="0" max="100" step="5" value={draft.carrier} onChange={e=>setDraft({...draft,carrier:+e.target.value,mix:1})} /></label>
  <label className="range-label">Tone cutoff <strong>{draft.cutoff} Hz</strong><input aria-label="Tone cutoff" type="range" min="1200" max="20000" step="100" value={draft.cutoff} onChange={e=>setDraft({...draft,cutoff:+e.target.value,mix:1})} /></label>
  <div className="settings-actions"><button className="btn btn-primary" disabled={busy} onClick={()=>apply(draft)}>{busy?'Applying…':'Apply effect'}</button><button className="btn btn-secondary" disabled={busy} onClick={()=>{setDraft(NATURAL);void apply(NATURAL);}}>Use natural voice</button></div>
  <p className="settings-copy" role="status">Current: {value.mix===0?'Natural · effects off':value.name}</p>
  <div className="settings-actions"><button className="btn btn-secondary" onClick={()=>{try{save(draft);}catch(e){setError(String(e));}}}>Save preset</button><button className="btn btn-secondary" onClick={()=>{try{downloadFile('imicall-voice.json',JSON.stringify(validateVoicePreset(draft),null,2));}catch(e){setError(String(e));}}}>Export preset</button><label className="btn btn-secondary file-button">Import preset<input type="file" accept="application/json,.json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>8192)throw new Error('Preset file is too large.');const p=validateVoicePreset(JSON.parse(await file.text()));setImported(p);setError('');}catch(err){setError(err instanceof Error?err.message:'Invalid file');}e.target.value='';}} /></label></div>
  {imported&&<div className="backup-preview"><h3>Review imported preset</h3><p>{imported.name}</p><p className="settings-copy">Pitch {imported.pitch} · Robot {imported.carrier} Hz · Cutoff {imported.cutoff} Hz · Effect {Math.round(imported.mix*100)}%</p><button className="btn btn-primary" onClick={()=>{setDraft(imported);setImported(null);setError('Preset loaded into the editor only. Save it to keep it; Apply effect changes your call.');}}>Use in editor</button><button className="btn btn-secondary" onClick={()=>setImported(null)}>Cancel import</button></div>}
  <label className="range-label">Effect amount <strong>{Math.round(draft.mix*100)}%</strong><input aria-label="Effect amount" type="range" min="0" max="1" step="0.05" value={draft.mix} onChange={e=>setDraft({...draft,mix:+e.target.value})}/></label>
  <details className="transfer-guide"><summary>How to create and share a voice preset</summary><ol><li>Choose Low voice, Radio or Robot as a starting point.</li><li>Give your preset a new name. Pitch changes how high or low the voice sounds. Robot tone adds modulation; 0 turns it off. Tone cutoff reduces high frequencies.</li><li>Set Effect amount. At 0% effects are off; below 100% some natural voice is mixed in.</li><li>Choose Save preset to keep your design locally. Export preset downloads the editor’s settings, even if they are not currently applied.</li><li>In another browser choose Import preset, review the values, then Use in editor. Save it if you want to keep it.</li><li>Apply effect explicitly when ready, including during a call. Use natural voice disables effects. Try with someone you trust and check that speech is understandable.</li></ol><p>Example: Pitch −3, Robot tone 40 Hz, cutoff 3500 Hz, effect 100%. This is a creative audio effect, not proof of anonymity. JSON files contain numeric settings, no audio, contact secrets or executable plugins. Up to 20 custom presets are kept.</p></details>
  {error&&<p className="permission-error" role="alert">{error}</p>}
  <p className="settings-copy">An effect does not make your voice anonymous or impossible to recognise. Imported presets are numeric settings only; no code is executed. Importing never turns an effect on.</p>
 </section>;
}
